"""
wp_autopilot/models.py
Shared data structures used across the pipeline.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class QueuedPost:
    """A blog post waiting to be scheduled."""
    title: str
    content: str                           # raw markdown or HTML
    category: str = ""                     # comma-sep category names
    tags: str = ""                         # comma-sep tag names
    seo_keyword: str = ""                  # focus keyword hint
    publish_date: str = ""                 # ISO date string or empty = auto-schedule
    status: str = "ready"
    priority: int = 999
    source_row: int = 0                    # row index in source file/sheet

    # Fields filled in by enricher
    seo_title: str = ""
    seo_description: str = ""
    seo_slug: str = ""
    seo_tags: list[str] = field(default_factory=list)
    excerpt: str = ""
    content_html: str = ""                 # converted from markdown

    # Fields filled in by scheduler
    scheduled_datetime: Optional[datetime] = None

    # Fields filled in after posting
    wp_post_id: Optional[int] = None
    wp_post_url: str = ""
    wp_scheduled_date: str = ""

    @property
    def category_list(self) -> list[str]:
        return [c.strip() for c in self.category.split(",") if c.strip()]

    @property
    def tag_list(self) -> list[str]:
        raw = [t.strip() for t in self.tags.split(",") if t.strip()]
        # merge with AI-suggested seo_tags, deduplicate
        combined = list(dict.fromkeys(raw + self.seo_tags))
        return combined


@dataclass
class EnrichedSEO:
    """SEO fields generated by DeepSeek."""
    seo_title: str
    seo_description: str
    slug: str
    focus_keyword: str
    suggested_tags: list[str]
    excerpt: str
    og_description: str


@dataclass
class ScheduleResult:
    """Result of scheduling one post to WordPress."""
    post: QueuedPost
    success: bool
    wp_post_id: Optional[int] = None
    wp_post_url: str = ""
    scheduled_date: str = ""
    error: str = ""
